export const BLOG_FETCH_SINGLE = "BLOG_FETCH_SINGLE"
export const BLOG_FETCH_SINGLE_FAILED = "BLOG_FETCH_SINGLE_FAILED"

export const BLOG_FETCH_ALL = "BLOG_FETCH_ALL"
export const BLOG_FETCH_ALL_FAILED = "BLOG_FETCH_ALL_FAILED"

export const BLOG_PAGINATION_FETCH_ALL = "BLOG_PAGINATION_FETCH_ALL"
