export const CONTACT_QUERY_CREATE = "CONTACT_QUERY_CREATE"
export const CONTACT_QUERY_RESET = "CONTACT_QUERY_RESET"
export const CONTACT_QUERY_SUCCESS = "CONTACT_QUERY_SUCCESS"
export const CONTACT_QUERY_FAILED = "CONTACT_QUERY_FAILED"
