export const CONTACT_QUERY_CREATE = "CONTACT_QUERY_CREATE"
export const CONTACT_QUERY_SUCCESS = "CONTACT_QUERY_SUCCESS"
export const CONTACT_QUERY_FAILED = "CONTACT_QUERY_FAILED"
export const CLEAR_CONTACT_ERRORS = "CLEAR_CONTACT_ERRORS"

export const SUBSCRIBING_NEWSLETTER = "SUBSCRIBING_NEWSLETTER"
export const SUBSCRIBING_NEWSLETTER_SUCCESS = "SUBSCRIBING_NEWSLETTER_SUCCESS"
export const SUBSCRIBING_NEWSLETTER_FAILED = "SUBSCRIBING_NEWSLETTER_FAILED"
export const CLEAR_SUBSCRIBE_ERRORS = "CLEAR_SUBSCRIBE_ERRORS"
