export const JOB_CREATE = 'JOB_CREATE'
export const JOB_CREATE_RESET = 'JOB_CREATE_RESET'
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS'
export const JOB_CREATE_FAILED = 'JOB_CREATE_FAILED'

export const JOB_FETCH_SINGLE = 'JOB_FETCH_SINGLE'
export const JOB_FETCH_SINGLE_FAILED = 'JOB_FETCH_SINGLE_FAILED'

export const JOB_FETCH_ALL = 'JOB_FETCH_ALL'
export const JOB_FETCH_ALL_FAILED = 'JOB_FETCH_ALL_FAILED'

export const JOB_PAGINATION_FETCH_ALL = 'JOB_PAGINATION_FETCH_ALL'

export const JOB_APPLY = 'JOB_APPLY'
export const JOB_APPLY_CANCEL = 'JOB_APPLY_CANCEL'

export const JOB_FETCH_RECRUITER = 'JOB_FETCH_RECRUITER'
export const JOB_FETCH_RECRUITER_FAILED = 'JOB_FETCH_RECRUITER_FAILED'
