export const USER_PROFILE_FETCH = "USER_PROFILE_FETCH"
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE"

export const USER_RECRUITER_ORG_ADD = "USER_PROFILE_ADD"
export const USER_RECRUITER_ORG_UPDATE = "USER_PROFILE_UPDATE"

export const USER_JOBSEEKER_SKILL_ADD = "USER_JOBSEEKER_SKILL_ADD"
export const USER_JOBSEEKER_SKILL_UPDATE = "USER_JOBSEEKER_SKILL_UPDATE"
