export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"
export const USER_LOAD_FAILED = "USER_LOAD_FAILED"

export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS"
export const PROFILE_LOAD_FAILED = "PROFILE_LOAD_FAILED"

export const RECRUITER_ORG_LOAD = "RECRUITER_ORG_LOAD"
export const RECRUITER_ORG_LOAD_FAILED = "RECRUITER_ORG_LOAD_FAILED"
