export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"
export const USER_LOAD_FAILED = "USER_LOAD_FAILED"

export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS"
export const PROFILE_LOAD_FAILED = "PROFILE_LOAD_FAILED"

// export const USER_RECRUITER_ORG_ADD = "USER_PROFILE_ADD"
// export const USER_RECRUITER_ORG_UPDATE = "USER_PROFILE_UPDATE"

// export const USER_JOBSEEKER_SKILL_ADD = "USER_JOBSEEKER_SKILL_ADD"
// export const USER_JOBSEEKER_SKILL_UPDATE = "USER_JOBSEEKER_SKILL_UPDATE"
